# Verdaccio configuration file
storage: C:/Users/james/codehub/chat-mcp/.verdaccio/storage
plugins: C:/Users/james/codehub/chat-mcp/.verdaccio/plugins

auth:
  htpasswd:
    file: C:/Users/james/codehub/chat-mcp/.verdaccio/htpasswd
    max_users: -1

uplinks:
  npmjs:
    url: 'http://127.0.0.1'

packages:
  '@*/*':
    access: $all
    publish: $all     
    unpublish: $all   
    proxy: npmjs
  '**':
    access: $all
    publish: $all     
    unpublish: $all 
    proxy: npmjs
  '/*':
    access: $all
    publish: $all     
    unpublish: $all   
    proxy: npmjs

server:
  keepAliveTimeout: 60
  allowHosts:
    - localhost
    - 127.0.0.1
    - '::1'
